export default [
    {
        name: 'H',
        color: 'white',
        mass: 1,
        charge: 0,
        Z: 1
    },
    {
        name: 'He',
        color: 'lightgray',
        mass: 4,
        charge: 0,
        Z: 2
    },
    {
        name: 'Li',
        color: 'gray',
        mass: 9,
        charge: 0,
        Z: 3,
    },
    {
        name: 'Be',
        color: 'darkgray',
        mass: 9,
        charge: 0,
        Z: 4,
    },
    {
        name: 'B',
        color: 'orange',
        mass: 11,
        charge: 0,
        Z: 5,
    },
    {
        name: 'C',
        color: 'black',
        mass: 12,
        charge: 0,
        Z: 6,
    },
    {
        name: 'N',
        color: 'aqua',
        mass: 14,
        charge: 0,
        Z: 7,
    },
    {
        name: 'O',
        color: 'red',
        mass: 16,
        charge: 0,
        Z: 8,
    },
    {
        name: 'Na',
        color: 'yellow',
        mass: 23,
        charge: 0,
        Z: 11,
    },
    {
        name: 'Mg',
        color: 'magenta',
        mass: 24,
        charge: 0,
        Z: 12,
    },
    {
        name: 'Al',
        color: '#c5c8de',
        mass: 27,
        charge: 0,
        Z: 13,
    },
    {
        name: 'Si',
        color: '#2b2c30',
        mass: 28,
        charge: 0,
        Z: 14,
    },
    {
        name: 'P',
        color: '#8ccf74',
        mass: 31,
        charge: 0,
        Z: 15,
    },
    {
        name: 'S',
        color: '#a6a10a',
        mass: 32,
        charge: 0,
        Z: 16,
    },
];